REQUEST_PATH = '/Users/ashnajain/Desktop/pythonSTN/tds/p3_w3_scenario/request.json'
INITIAL_SCHEDULE_PATH = ''
TRAVEL_MATRIX_PATH = '/Users/ashnajain/Desktop/pythonSTN/tds/p3_w3_scenario/travel_matrix.json'
EPOCH_DATE = '2025-05-19T00:00'
GLOBAL_START = "2026-01-14T08:00"
GLOBAL_END = "2026-01-20T23:00"
MIN_HOME_TIME = 60
TRANSPORT_REQUEST_OUTPUT_PATH = '/Users/ashnajain/Desktop/pythonSTN/tds/transport_requests_output.json'
MAX_ADDITIONAL_RIDE_TIME = 40  # minutes